import json
import os
import sys
import argparse

def flatten_json(y):
    out = {}
    def flatten(x, name=''):
        if isinstance(x, dict):
            for a in x:
                flatten(x[a], name + a + '.')
        elif isinstance(x, list):
            out[name[:-1]] = str(x)
        else:
            out[name[:-1]] = x
    flatten(y)
    return out

def convert_to_strings_file_content(flat_json):
    """Converts a flat dictionary to a .strings file content string."""
    strings_content = []
    for key, value in flat_json.items():
        # Escape double quotes and backslashes in the value
        escaped_value = str(value).replace('\\', '\\\\').replace('"', '\\"')
        strings_content.append(f'"{key}" = "{escaped_value}";')
    return "\n".join(strings_content)

def main():
    parser = argparse.ArgumentParser(description='Convert web i18n JSON to iOS .strings files.')
    parser.add_argument('stock_app_path', help='The path to the StockApp directory containing the Locales folder.')
    args = parser.parse_args()

    # The script is in iOSApp/Scripts, so we need to go up one level to get to the iOSApp root.
    ios_app_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    
    stock_app_dir = args.stock_app_path
    web_locales_path_tw = os.path.join(stock_app_dir, 'Locales', 'zh-TW', 'translation.json')
    web_locales_path_en = os.path.join(stock_app_dir, 'Locales', 'en', 'translation.json')

    # Define correct output paths for the .strings files based on the new structure
    ios_en_lproj_dir = os.path.join(ios_app_root, 'Sources', 'iOSApp', 'Resources', 'en.lproj')
    ios_zh_hant_lproj_dir = os.path.join(ios_app_root, 'Sources', 'iOSApp', 'Resources', 'zh-Hant.lproj')
    
    ios_strings_path_en = os.path.join(ios_en_lproj_dir, 'Localizable.strings')
    ios_strings_path_zh_hant = os.path.join(ios_zh_hant_lproj_dir, 'Localizable.strings')
    
    print(f"Corrected English output path: {os.path.normpath(ios_strings_path_en)}")
    print(f"Corrected Traditional Chinese output path: {os.path.normpath(ios_strings_path_zh_hant)}")

    try:
        with open(web_locales_path_tw, 'r', encoding='utf-8') as f:
            web_json_tw = json.load(f)

        with open(web_locales_path_en, 'r', encoding='utf-8') as f:
            web_json_en = json.load(f)

        flat_data_tw = flatten_json(web_json_tw)
        flat_data_en = flatten_json(web_json_en)
        
        # Add comment headers
        comment_header = "// Generated by convert_locales.py. Do not edit manually.\n\n"
        
        strings_content_en = convert_to_strings_file_content(flat_data_en)
        strings_content_zh_hant = convert_to_strings_file_content(flat_data_tw)

        # Ensure directories exist
        os.makedirs(ios_en_lproj_dir, exist_ok=True)
        os.makedirs(ios_zh_hant_lproj_dir, exist_ok=True)

        with open(ios_strings_path_en, 'w', encoding='utf-8') as f:
            f.write(comment_header)
            f.write(strings_content_en)
        
        with open(ios_strings_path_zh_hant, 'w', encoding='utf-8') as f:
            f.write(comment_header)
            f.write(strings_content_zh_hant)

        print(f"成功轉換並建立 en.lproj 和 zh-Hant.lproj 的 Localizable.strings 檔案。")

    except FileNotFoundError as e:
        print(f"錯誤: 找不到輸入檔案 {e.filename}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"發生未預期的錯誤: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main() 